# Generated by Django 3.2.4 on 2021-07-02 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumers', '0002_auto_20210617_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='invited_users',
            field=models.ManyToManyField(related_name='invited_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
